let websitData = {
    "menu":[
        {"name":"首页","url":"javascript:;","children":[
            {"name":null,"url":null,"children":[
                {"name":null,"url":null}
            ]}
        ]},
        {"name":"关于我们","url":"javascript:;","children":[
            {"name":"公司简介","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"企业文化","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"荣誉资质","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"厂房环境","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]}
        ]},
        {"name":"产品中心","url":"javascript:;","children":[
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
        ]},
        {"name":"新闻资讯","url":"javascript:;","children":[
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
        ]},
        {"name":"视频中心","url":"javascript:;","children":[
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
        ]},
        {"name":"工程案例","url":"javascript:;","children":[
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
        ]},
        {"name":"在线留言","url":"javascript:;","children":[
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
        ]},
        {"name":"联系我们","url":"javascript:;","children":[
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
            {"name":"产品分类","url":"javascript:;","children":[
                {"name":null,"url":null}
            ]},
        ]}
    ],
    "proClass":[
        {"name":"螺旋式空气压缩机","summary":"全智能驱动 无齿传动","url":"javascript:;"},
        {"name":"活塞式空气压缩机","summary":"特有双控系统，电控与气控结合","url":"javascript:;"},
        {"name":"后部处理设备","summary":"国家工信部“能效之星”产品","url":"javascript:;"},
        {"name":"优质配件","summary":"优秀品质，值得信赖","url":"javascript:;"}
    ],
    "proList":[
        {"name":"螺杆式空压机BP01","summary":null,"url":"javascript:;","image":"img/pro1.jpg"},
        {"name":"螺杆式空压机BP02","summary":null,"url":"javascript:;","image":"img/pro1.jpg"},
        {"name":"螺杆式空压机BP03","summary":null,"url":"javascript:;","image":"img/pro1.jpg"},
        {"name":"螺杆式空压机BP04","summary":null,"url":"javascript:;","image":"img/pro1.jpg"},
        {"name":"螺杆式空压机BP05","summary":null,"url":"javascript:;","image":"img/pro1.jpg"},
        {"name":"螺杆式空压机BP06","summary":null,"url":"javascript:;","image":"img/pro1.jpg"},
    ],
}